name: Build TD files

on:
  push:
    branches:
      - master

jobs:
  build-td-files:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Create output directory
      run: mkdir output

    - name: Pandoc
      uses: docker://pandoc/core:2.9
      with:
        args: >-
          -s -N
          -f markdown
          -t latex
          -o output/1.tex
          td/1.md

    - name: LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        working_directory: output
        root_file: 1.tex

    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: td1
        path: output/1.pdf

