name: build TD files

on:
  push:
    branches:
      - inkscape

jobs:
  convert-via-pandoc:
    runs-on: ubuntu-latest
    container:

      image: docker://pandoc/core:2.9
      options: --entrypoint=sh

    steps:

    - name: checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: create output directories
      run: mkdir output

    - name: convert md to tex
      run: |
        find ./ -iname '*.md' -type f -exec sh -c 'pandoc -s -N ${0} -o output/$(basename $0 .md).tex' {} \;

    - name: LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        working_directory: output
        root_file: "*.tex"
        glob_root_file: true

    - name: artifacts
      uses: actions/upload-artifact@v2
      with:
        name: files
        path: output/*.pdf

  convert-via-inkscape:
    runs-on: ubuntu-latest
    container:

      image: docker://johnodon/inkscape
      options: --entrypoint=sh

    steps:

    - name: checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: create output directories
      run: mkdir output

    - name: convert svg to pdf
      run: |
        find ./ -iname '*.svg' -type f -exec sh -c 'inkscape --export-area-drawing --without-gui --export-pdf=output/$(basename $0 .svg).pdf --file=${0}' {} \;

    - name: artifacts
      uses: actions/upload-artifact@v2
      with:
        name: images
        path: output/*.pdf

