name: Build TD files

on:
  push:
    branches:
      - gh-action-array

jobs:
  convert-via-pandoc:
    runs-on: ubuntu-latest
    container:
      image: docker://pandoc/core:2.9
      options: --entrypoint=sh
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: create output directories
      run: |
        for d in */; do
          mkdir -p output/$d
        done
    - name: convert md to tex
      run: |
        find ./ -iname '*.md' -type f -exec sh -c 'pandoc ${0} -o output/${0%.md}.tex' {} \;
    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: td
        path: output

