name: Build TD files

on:
	push:
		branches:
			- artifacts

jobs:
	build-td-files:
		runs-on: ubuntu-latest
		steps:

		- name: Checkout
			uses: actions/checkout@v2
			with:
				persist-credentials: false

		- name: Archive production artifacts
				uses: actions/upload-artifact@v2
				with:
					name: td1
					path: td/1.md

